server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server（seata服务器中的配置文件file.conf）中的对应（一致）
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        #nacos服务注册中心地址
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account
    username: root
    password: ljw961206


#在feign中关闭hystrix
feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info


mybatis:
  mapperLocations: classpath:mapper/*.xml